### ISSUE TITLE
Legal: Check the right to distribute

### ISSUE THREAD

**Issue by dleidert** [mwt/zoom-apt-repo#13]
Hi,

I believe that you need to check the legality of what you are attempting to do here.

The author of a software must have given you the permission to (re)distribute it for you to be allowed to do that. Independent of your intention, I believe that the Zoom license does not contain such permission.

**Comment by mwt** [comment]
There are many unofficial projects which redistribute Zoom such as the snap, the flatpak, and the AUR package. I asked them about it in 2022 and they were very supportive.

The Pop! OS nonfree repo does a cool thing where they redirect to original download links instead of serving the files themselves. I could pivot to that if Zoom changes their stance.
