### ISSUE TITLE
Better location for your GPG key

### ISSUE THREAD

**Issue by mfonville** [mwt/zoom-apt-repo#5]
Manually installed apt-keys are normally stored in `/etc/apt/trusted.gpg.d/`  (those in `/usr/share/keyrings` ought to be managed in a package)
I would suggest to download your key and store it there with:
`wget -qO- https://mirror.mwt.me/my/gpgkey | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/mwt.gpg`
and to update the path in the `.list` accordingly to that path.

**Comment by mwt** [comment]
> Manually installed apt-keys are normally stored in /etc/apt/trusted.gpg.d/ (those in /usr/share/keyrings ought to be managed in a package)

Hi! Thanks for contributing. I don't agree with this. The `trusted.gpg.d` folder is not scoped. So, putting my cert there means that you trust my signature for any repo.

Using the keyrings folder does not have this effect.

I got this recommendation from the Debian wiki, and I think it makes sense. I'm open to suggestions though on the directory. I only use `/usr/share/keyrings` because it exists by default on Ubuntu/Debian.

**Comment by mfonville** [comment]
You are right, that `trusted.gpg.d` is deprecated because of scoping. I hadn't caught on to that yet.
But then it should be put in `/etc/apt/keyrings` instead (which is also described in 
 https://wiki.debian.org/DebianRepository/UseThirdParty and also there it is mentioned only to use `/usr/share/keyrings` if the certificate is going to be managed by an apt/dpkg package  )
 They also mention there: _In releases older than Debian 12 and Ubuntu 22.04, `/etc/apt/keyrings` does not exist by default. It SHOULD be created with permissions 0755 if it is needed and does not already exist._
 

Thank you for maintaining this repository, and I hope this can help :-)

**Comment by mwt** [comment]
That sounds right to me. Thanks!
