### ISSUE TITLE
New zoom version

### ISSUE THREAD

**Issue by trois-six** [mwt/zoom-apt-repo#6]
Hello!

FYI, a new version of zoom (5.14.0 build 1720) has been released 10 days ago, and it's not replicated in your repo. Maybe your task to check the new version twice a day is not executed anymore?

https://zoom.us/client/latest/zoom_amd64.deb is always the good URL.

Thank you for the repo.

**Comment by mwt** [comment]
Thanks!

Yes. It was failing because of a breaking change made in the formatting of rclone releases which caused the rclone repo to not build. This raised an error and prevented this script from running.

I've bypassed it with this commit to the parent script:

https://github.com/mwt/mirror-scripts/commit/e13e5535c6779c9f98f87f234d1b378d952ed9a2

There is no reason to `set -e` here because an error in one line shouldn't necessarily stop the others from running.

**Comment by trois-six** [comment]
Ok, thank you! I think I can close this issue then.
